spring:
  application:
    name: credit-application
  datasource:
    url: jdbc:h2:mem:credit-application-db
    username: username
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
